name: Run Jupyter Notebook

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Adjust if a different Python version is required

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python install_requirements.py  # Runs your script to install dependencies

    - name: Install Jupyter and Papermill
      run: python -m pip install jupyter papermill

    - name: Execute Notebook
      run: |
        papermill your_notebook.ipynb output_notebook.ipynb
