name: Run Jupyter Notebook

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Adjust Python version as needed

    # Step 3: Install Dependencies
    - name: Install Required Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter ipykernel papermill

    # Step 4: Debug Python Path
    - name: Debug Python Path
      run: |
        which python
        python --version

    # Step 5: Optional Kernel Setup
    - name: Set up Jupyter Kernels (if applicable)
      run: |
        if [ -f scripts/setup_kernels.py ]; then
          python scripts/setup_kernels.py
        else
          echo "Kernel setup script not found, skipping this step."
        fi # Closing the if block properly
      continue-on-error: true # Avoid failure if the script isn't required

    # Step 6: Execute Jupyter Notebook
    - name: Execute Notebook
      run: |
        NOTEBOOK_NAME="customer-segmentation-recommendation-system.ipynb"
        OUTPUT_NOTEBOOK="output_notebook.ipynb"
        if [ -f "$NOTEBOOK_NAME" ]; then
          papermill "$NOTEBOOK_NAME" "$OUTPUT_NOTEBOOK"
          echo "Notebook executed successfully: $OUTPUT_NOTEBOOK"
        else
          echo "Notebook $NOTEBOOK_NAME not found!"
          exit 1
        fi # Closing the if block properly
