name: Run Jupyter Notebook

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install git-lfs and Pull Large Files
    - name: Install and Set Up git-lfs
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install
        git lfs pull

    # Step 4: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy>=1.21.0 pandas>=1.3.0 seaborn>=0.11.2 matplotlib>=3.4.0 \
            plotly>=5.0.0 scipy>=1.7.0 scikit-learn>=0.24.2 yellowbrick>=1.3 \
            tabulate>=0.8.9 jupyter>=1.0.0 ipykernel>=6.5.0 papermill>=2.4.0 \
            pytest>=6.0.0 black>=21.0.0 flake8>=3.9.0

    # Step 5: Execute Jupyter Notebook
    - name: Execute Notebook
      run: |
        NOTEBOOK_NAME="customer-segmentation-recommendation-system.ipynb"
        OUTPUT_NOTEBOOK="output_notebook.ipynb"
        if [ -f "$NOTEBOOK_NAME" ]; then
          papermill "$NOTEBOOK_NAME" "$OUTPUT_NOTEBOOK"
          echo "Notebook executed successfully: $OUTPUT_NOTEBOOK"
        else
          echo "Notebook $NOTEBOOK_NAME not found!"
          exit 1
        fi

    # Step 6: Run Linting and Testing
    - name: Run Linting and Tests
      run: |
        flake8 .
        black --check .
        pytest
